"use client";

import {FormEvent,useEffect,useMemo,useRef,useState} from "react";
import {CircleMarker,GeoJSON,MapContainer,TileLayer,Tooltip,ZoomControl,useMap,useMapEvents} from "react-leaflet";
import type {Feature,GeoJsonObject,Geometry} from "geojson";
import type {Layer} from "leaflet";
import L from "leaflet";

import {assessmentPathStyle,assessmentPointStyle} from "./assessment-map-style";
import {AssessmentAttributeTable,featuresOf,type SelectedMapFeature} from "./assessment-attribute-table";
import {GeoLearnBasemap,basemapRuntime} from "./map-basemap";
import {configuredMapInteractions,mapInteractionsForActivityConfig,normalizeMapExperience,type MapInteraction} from "@/features/questions/experience";
import styles from "./assessment-map-navigation.module.css";

type Bbox=[number,number,number,number];
type RasterLayerInfo={tileUrl:string;attribution:string;sensor:string|null;acquiredAt:string|null;temporalLabel:string|null;sourceLabel:string|null};
type MapLayer={
  datasetVersionId:string;title:string;role:"SOURCE"|"TARGET"|"CONTEXT";visible:boolean;opacity:number;bbox:Bbox|null;style:Record<string,unknown>;
  dataKind?:"VECTOR"|"RASTER"|"TABLE";format?:string|null;geojson:GeoJsonObject|null;raster?:RasterLayerInfo|null;
};
type VectorMapLayer=MapLayer&{geojson:GeoJsonObject};
type AnalysisLayer={toolId:string;title:string;geojson:GeoJsonObject|null};
type Payload={layers:MapLayer[];bbox:Bbox|null};
type SearchResult={id:string;label:string;lat:number;lon:number;type:string|null};
type NavTarget={lat:number;lon:number;label:string}|null;
type LabelPresentation={field:string|null;minZoom:number;mode:"configured"|"auto"|"off"};
type DataPanelContent={layerTitle:string;role:MapLayer["role"];entries:Array<[string,string]>}|null;

const DEFAULT_LABEL_MIN_ZOOM=11;
const LABEL_FIELD_PRIORITY=["name","nama","title","label","school_name","nama_sekolah","zone","zona","region","wilayah"];
function isVectorLayer(layer:MapLayer):layer is VectorMapLayer{return layer.dataKind!=="RASTER"&&Boolean(layer.geojson);}
function fitMapToBbox(map:L.Map,bbox:Bbox){map.fitBounds([[bbox[1],bbox[0]],[bbox[3],bbox[2]]],{padding:[24,24],maxZoom:16});}
function combinedBbox(layers:MapLayer[]):Bbox|null{const boxes=layers.map((layer)=>layer.bbox).filter((bbox):bbox is Bbox=>Array.isArray(bbox)&&bbox.length===4&&bbox.every(Number.isFinite));if(!boxes.length)return null;return [Math.min(...boxes.map((x)=>x[0])),Math.min(...boxes.map((x)=>x[1])),Math.max(...boxes.map((x)=>x[2])),Math.max(...boxes.map((x)=>x[3]))];}
function FitToData({bbox}:{bbox:Bbox|null}){const map=useMap();if(!bbox)return null;return <button className="runtime-fit-button" type="button" onClick={(event)=>{event.stopPropagation();fitMapToBbox(map,bbox);}}>Fit ke data</button>;}
function AutoFitToData({bbox}:{bbox:Bbox|null}){const map=useMap();const fitted=useRef(false);useEffect(()=>{if(!bbox||fitted.current)return;fitted.current=true;const frame=requestAnimationFrame(()=>fitMapToBbox(map,bbox));return()=>cancelAnimationFrame(frame);},[bbox,map]);return null;}
function MapZoomTracker({onZoom}:{onZoom:(zoom:number)=>void}){const map=useMapEvents({zoomend(){onZoom(map.getZoom());}});useEffect(()=>{onZoom(map.getZoom());},[map,onZoom]);return null;}
function NavigateToTarget({target}:{target:NavTarget}){const map=useMap();useEffect(()=>{if(target)map.flyTo([target.lat,target.lon],Math.max(map.getZoom(),14),{duration:.8});},[map,target]);return null;}
function NavigateToFeature({selected,layers}:{selected:SelectedMapFeature;layers:VectorMapLayer[]}){const map=useMap();useEffect(()=>{if(!selected)return;const layer=layers.find((item)=>item.datasetVersionId===selected.layerId);if(!layer)return;const feature=featuresOf(layer.geojson)[selected.featureIndex];if(!feature)return;const featureLayer=L.geoJSON(feature);const bounds=featureLayer.getBounds();if(bounds.isValid())map.fitBounds(bounds.pad(.35),{maxZoom:16,padding:[36,36]});},[layers,map,selected]);return null;}
function CoordinateTracker({pickEnabled,readoutEnabled,onPick,onReadout}:{pickEnabled:boolean;readoutEnabled:boolean;onPick:(lat:number,lon:number)=>void;onReadout:(lat:number,lon:number)=>void}){useMapEvents({mousemove(event){if(readoutEnabled)onReadout(event.latlng.lat,event.latlng.lng);},click(event){if(pickEnabled)onPick(event.latlng.lat,event.latlng.lng);}});return null;}
function bindSafePopup(feature:Feature<Geometry>,layer:Layer){const entries=Object.entries(feature.properties??{}).filter(([,value])=>value===null||["string","number","boolean"].includes(typeof value)).slice(0,12);if(!entries.length)return;const content=document.createElement("dl");content.className="runtime-feature-popup";for(const [key,value] of entries){const term=document.createElement("dt");term.textContent=key;const detail=document.createElement("dd");detail.textContent=value===null?"—":String(value);content.append(term,detail);}layer.bindPopup(content);}
function detectedLabelField(geojson:GeoJsonObject):string|null{const features=featuresOf(geojson);const keys=new Map<string,string>();for(const feature of features.slice(0,100)){for(const [key,value] of Object.entries(feature.properties??{})){if(value===null||!["string","number"].includes(typeof value))continue;keys.set(key.toLowerCase(),key);}}for(const candidate of LABEL_FIELD_PRIORITY){const match=keys.get(candidate);if(match)return match;}return null;}
function labelPresentation(layer:VectorMapLayer):LabelPresentation{if(Object.prototype.hasOwnProperty.call(layer.style??{},"label")){const raw=(layer.style as {label?:unknown}).label;if(!raw||typeof raw!=="object")return {field:null,minZoom:DEFAULT_LABEL_MIN_ZOOM,mode:"off"};const label=raw as {enabled?:unknown;field?:unknown;minZoom?:unknown};if(label.enabled!==true)return {field:null,minZoom:DEFAULT_LABEL_MIN_ZOOM,mode:"off"};const field=typeof label.field==="string"&&label.field.trim()?label.field.trim():null;const rawZoom=Number(label.minZoom??DEFAULT_LABEL_MIN_ZOOM);const minZoom=Number.isFinite(rawZoom)?Math.min(22,Math.max(0,Math.round(rawZoom))):DEFAULT_LABEL_MIN_ZOOM;return {field,minZoom,mode:field?"configured":"off"};}const field=detectedLabelField(layer.geojson);return {field,minZoom:DEFAULT_LABEL_MIN_ZOOM,mode:field?"auto":"off"};}
function bindFeatureLabel(feature:Feature<Geometry>,layer:Layer,field:string,className:string){const value=feature.properties?.[field];if(value===null||value===undefined||(typeof value!=="string"&&typeof value!=="number"))return;const text=String(value).trim();if(!text)return;const content=document.createElement("span");content.textContent=text.length>80?`${text.slice(0,77)}…`:text;const point=feature.geometry.type==="Point"||feature.geometry.type==="MultiPoint";layer.bindTooltip(content,{permanent:true,direction:point?"right":"center",offset:point?[8,0]:[0,0],className,interactive:false,opacity:.94});}
function analysisStyle(toolId:string):L.PathOptions{if(toolId==="buffer")return {color:"#d97706",fillColor:"#f59e0b",weight:3,dashArray:"7 5",fillOpacity:.22};if(toolId==="overlay")return {color:"#7c3aed",fillColor:"#8b5cf6",weight:4,fillOpacity:.38};return {color:"#db2777",weight:4,dashArray:"10 6",fillOpacity:.08};}
function analysisPointStyle(toolId:string){const style=analysisStyle(toolId);return {radius:8,color:String(style.color),fillColor:String(style.fillColor??style.color),fillOpacity:.85,weight:3};}
function analysisColor(toolId:string){if(toolId==="buffer")return "#d97706";if(toolId==="overlay")return "#7c3aed";return "#db2777";}
function validCoordinate(lat:number,lon:number){return Number.isFinite(lat)&&Number.isFinite(lon)&&lat>=-90&&lat<=90&&lon>=-180&&lon<=180;}
function dataPanelContent(selected:SelectedMapFeature,layers:VectorMapLayer[]):DataPanelContent{if(!selected)return null;const layer=layers.find((item)=>item.datasetVersionId===selected.layerId);if(!layer)return null;const feature=featuresOf(layer.geojson)[selected.featureIndex];if(!feature)return null;const entries=Object.entries(feature.properties??{}).filter(([,value])=>value===null||["string","number","boolean"].includes(typeof value)).slice(0,10).map(([key,value])=>[key,value===null?"—":typeof value==="boolean"?(value?"Ya":"Tidak"):String(value)] as [string,string]);return {layerTitle:layer.title,role:layer.role,entries};}
function experienceLabel(value:string){if(value==="analysis")return "Peta Analisis";if(value==="map-data")return "Peta + Data";return "Peta Tunggal";}
function rasterSummary(layer:MapLayer){const meta=layer.raster;if(!meta)return "RASTER";return meta.temporalLabel||meta.acquiredAt||meta.sensor||"RASTER";}

export function AssessmentLeafletMap({attemptId,questionVersionId,analyses,activityConfig}:{attemptId:string;questionVersionId:string;analyses:AnalysisLayer[];activityConfig:Record<string,unknown>;}){
  const [payload,setPayload]=useState<Payload|null>(null);const [error,setError]=useState("");const [visibility,setVisibility]=useState<Record<string,boolean>>({});const [analysisVisibility,setAnalysisVisibility]=useState<Record<string,boolean>>({});const [searchQuery,setSearchQuery]=useState("");const [searchResults,setSearchResults]=useState<SearchResult[]>([]);const [searching,setSearching]=useState(false);const [searchError,setSearchError]=useState("");const [latInput,setLatInput]=useState("");const [lonInput,setLonInput]=useState("");const [target,setTarget]=useState<NavTarget>(null);const [pickMode,setPickMode]=useState(false);const [readout,setReadout]=useState<{lat:number;lon:number}|null>(null);const [attributeOpen,setAttributeOpen]=useState(false);const [attributeLayerId,setAttributeLayerId]=useState("");const [selectedFeature,setSelectedFeature]=useState<SelectedMapFeature>(null);const [mapZoom,setMapZoom]=useState(5);
  const configuredInteractions=useMemo(()=>configuredMapInteractions(activityConfig),[activityConfig]);const interactionSet=useMemo(()=>new Set(mapInteractionsForActivityConfig(activityConfig)),[activityConfig]);const mapExperience=normalizeMapExperience(activityConfig.mapExperience);const basemap=basemapRuntime(activityConfig.basemap);const legacyMode=configuredInteractions===null;const enabled=(interaction:MapInteraction)=>interactionSet.has(interaction);const showSearch=enabled("search-place");const showGoToCoordinate=enabled("go-to-coordinate");const showPickCoordinate=enabled("pick-coordinate");const showPointer=enabled("pointer-coordinate");const showCoordinateBox=showGoToCoordinate||showPickCoordinate;const showToolbar=showSearch||showCoordinateBox||showPointer;const showLayerControl=enabled("layer-control");const showLegend=enabled("legend");const showPopup=enabled("popup");const showLabels=enabled("feature-labels");const showDataPanel=enabled("data-panel");const showAttributeTable=enabled("attribute-table");const showFit=enabled("fit-to-data");const showNorthArrow=enabled("north-arrow");
  useEffect(()=>{let active=true;fetch(`/api/assessment/attempts/${attemptId}/questions/${questionVersionId}/map`,{cache:"no-store"}).then(async(response)=>{const body=await response.json();if(!response.ok)throw new Error(body.error??"Peta tidak tersedia");if(active){const next=body as Payload;setPayload(next);const firstVector=next.layers.find(isVectorLayer);setAttributeLayerId((current)=>current||firstVector?.datasetVersionId||"");}}).catch((reason)=>{if(active)setError(reason instanceof Error?reason.message:"Peta tidak tersedia");});return()=>{active=false;};},[attemptId,questionVersionId]);
  const vectorLayers=useMemo(()=>payload?.layers.filter(isVectorLayer)??[],[payload]);const center=useMemo<[number,number]>(()=>{const bbox=payload?.bbox;return bbox?[(bbox[1]+bbox[3])/2,(bbox[0]+bbox[2])/2]:[-2.5,118];},[payload]);const labelPresentations=useMemo(()=>Object.fromEntries(vectorLayers.map((layer)=>[layer.datasetVersionId,labelPresentation(layer)])) as Record<string,LabelPresentation>,[vectorLayers]);const initialFitBbox=useMemo(()=>combinedBbox((payload?.layers??[]).filter((layer)=>layer.visible))??payload?.bbox??null,[payload]);const currentFitBbox=useMemo(()=>combinedBbox((payload?.layers??[]).filter((layer)=>visibility[layer.datasetVersionId]??layer.visible))??payload?.bbox??null,[payload,visibility]);const selectedData=useMemo(()=>dataPanelContent(selectedFeature,vectorLayers),[selectedFeature,vectorLayers]);
  async function searchPlace(event:FormEvent){event.preventDefault();const q=searchQuery.trim();if(q.length<2){setSearchError("Masukkan minimal 2 karakter.");return;}setSearching(true);setSearchError("");setSearchResults([]);try{const response=await fetch(`/api/map/search?q=${encodeURIComponent(q)}`,{cache:"no-store"});const body=await response.json() as {results?:SearchResult[];error?:string};if(!response.ok)throw new Error(body.error??"Pencarian gagal.");const results=body.results??[];setSearchResults(results);if(!results.length)setSearchError("Tempat tidak ditemukan.");}catch(reason){setSearchError(reason instanceof Error?reason.message:"Pencarian gagal.");}finally{setSearching(false);}}
  function chooseResult(result:SearchResult){setTarget({lat:result.lat,lon:result.lon,label:result.label});setLatInput(result.lat.toFixed(6));setLonInput(result.lon.toFixed(6));setSearchResults([]);}function goToCoordinate(){const lat=Number(latInput);const lon=Number(lonInput);if(!validCoordinate(lat,lon)){setSearchError("Koordinat tidak valid. Lat -90…90, lon -180…180.");return;}setSearchError("");setTarget({lat,lon,label:`${lat.toFixed(6)}, ${lon.toFixed(6)}`});}function pickCoordinate(lat:number,lon:number){setLatInput(lat.toFixed(6));setLonInput(lon.toFixed(6));setTarget({lat,lon,label:"Koordinat pilihan"});setPickMode(false);}
  if(error)return <div className="runtime-media-shell">{error}</div>;if(!payload)return <div className="runtime-map-shell"><div className="map-loading">Memuat DatasetVersion…</div></div>;
  return <div className={styles.workspace} data-map-experience={mapExperience}>
    <div className={styles.experienceBar}><span>{experienceLabel(mapExperience)} · {basemap.label}</span><small>{basemap.fallbackFrom?"Basemap tersimpan belum tersedia; memakai Street.":legacyMode?"Mode kompatibilitas soal lama":"Kontrol peta mengikuti konfigurasi soal"}</small></div>
    {showToolbar&&<section className={styles.toolbar} aria-label="Navigasi peta">{showSearch&&<form className={styles.searchBox} onSubmit={searchPlace}><label htmlFor={`place-search-${questionVersionId}`}>Cari tempat</label><div className={styles.inlineControls}><input id={`place-search-${questionVersionId}`} value={searchQuery} onChange={(event)=>setSearchQuery(event.target.value)} placeholder="Contoh: Pekanbaru, Riau"/><button type="submit" disabled={searching}>{searching?"Mencari…":"Cari"}</button></div>{searchResults.length>0&&<div className={styles.results}>{searchResults.map((result)=><button type="button" key={result.id} onClick={()=>chooseResult(result)}><strong>{result.label}</strong><small>{result.lat.toFixed(5)}, {result.lon.toFixed(5)}</small></button>)}</div>}</form>}{showCoordinateBox&&<div className={styles.coordinateBox}><span>Koordinat</span><div className={styles.coordinateInputs}><input inputMode="decimal" aria-label="Latitude" value={latInput} readOnly={!showGoToCoordinate} onChange={(event)=>setLatInput(event.target.value)} placeholder="Latitude"/><input inputMode="decimal" aria-label="Longitude" value={lonInput} readOnly={!showGoToCoordinate} onChange={(event)=>setLonInput(event.target.value)} placeholder="Longitude"/></div><div className={styles.inlineControls}>{showGoToCoordinate&&<button type="button" onClick={goToCoordinate}>Pergi</button>}{showPickCoordinate&&<button className={pickMode?styles.activeButton:""} type="button" onClick={()=>setPickMode((value)=>!value)}>{pickMode?"Klik peta…":"Ambil dari peta"}</button>}</div></div>}{showPointer&&<div className={styles.readout}><span>Pointer</span><strong>{readout?`${readout.lat.toFixed(5)}, ${readout.lon.toFixed(5)}`:"Gerakkan pointer di peta"}</strong>{target&&<small>Marker: {target.label}</small>}</div>}</section>}
    {searchError&&<div className={styles.error}>{searchError}</div>}
    <div className="runtime-leaflet-shell"><MapContainer key={`${questionVersionId}-${basemap.id}`} center={center} zoom={payload.bbox?8:5} className="runtime-product-map" scrollWheelZoom zoomControl={false}><ZoomControl position="bottomright"/><AutoFitToData bbox={initialFitBbox}/>{showFit&&<FitToData bbox={currentFitBbox}/>} {showLabels&&<MapZoomTracker onZoom={setMapZoom}/>} <NavigateToTarget target={target}/>{(showDataPanel||showAttributeTable)&&<NavigateToFeature selected={selectedFeature} layers={vectorLayers}/>} {(showPickCoordinate||showPointer)&&<CoordinateTracker pickEnabled={pickMode&&showPickCoordinate} readoutEnabled={showPointer} onPick={pickCoordinate} onReadout={(lat,lon)=>setReadout({lat,lon})}/>} <GeoLearnBasemap value={activityConfig.basemap}/>
      {payload.layers.filter((layer)=>layer.dataKind==="RASTER"&&layer.raster&&(visibility[layer.datasetVersionId]??layer.visible)).map((layer)=><TileLayer key={layer.datasetVersionId} url={layer.raster!.tileUrl} attribution={layer.raster!.attribution} opacity={layer.opacity} zIndex={120}/>) }
      {vectorLayers.filter((layer)=>(visibility[layer.datasetVersionId]??layer.visible)).map((layer)=>{let featureIndex=-1;const presentation=labelPresentations[layer.datasetVersionId]??{field:null,minZoom:DEFAULT_LABEL_MIN_ZOOM,mode:"off" as const};const labelsVisible=Boolean(showLabels&&presentation.field&&mapZoom>=presentation.minZoom);return <GeoJSON key={`${layer.datasetVersionId}-${selectedFeature?.layerId??"none"}-${selectedFeature?.featureIndex??-1}-${labelsVisible?"labels":"nolabels"}`} data={layer.geojson} style={(feature)=>{featureIndex+=1;const selected=selectedFeature?.layerId===layer.datasetVersionId&&selectedFeature.featureIndex===featureIndex;const base=feature?.geometry.type==="Point"||feature?.geometry.type==="MultiPoint"?assessmentPointStyle(layer.role,layer.opacity):assessmentPathStyle(layer.role,layer.opacity);return selected?{...base,color:"#0f172a",weight:5,fillOpacity:Math.max(Number(base.fillOpacity??0),.65)}:base;}} pointToLayer={(_feature,latlng)=>L.circleMarker(latlng,assessmentPointStyle(layer.role,layer.opacity))} onEachFeature={(feature,leafletLayer)=>{const typed=feature as Feature<Geometry>;const index=featuresOf(layer.geojson).indexOf(typed);if(showPopup)bindSafePopup(typed,leafletLayer);if(labelsVisible&&presentation.field)bindFeatureLabel(typed,leafletLayer,presentation.field,styles.featureLabel);if(showDataPanel||showAttributeTable){leafletLayer.on("click",()=>{if(index<0)return;setAttributeLayerId(layer.datasetVersionId);setSelectedFeature({layerId:layer.datasetVersionId,featureIndex:index});if(showAttributeTable)setAttributeOpen(true);});}}}><Tooltip sticky>{layer.title} · {layer.role}</Tooltip></GeoJSON>;})}
      {analyses.filter((analysis)=>analysis.geojson&&(analysisVisibility[analysis.toolId]??true)).map((analysis)=><GeoJSON key={analysis.toolId} data={analysis.geojson!} style={analysisStyle(analysis.toolId)} pointToLayer={(_feature,latlng)=>L.circleMarker(latlng,analysisPointStyle(analysis.toolId))} onEachFeature={(feature,layer)=>{if(showPopup)bindSafePopup(feature as Feature<Geometry>,layer);}}><Tooltip sticky>{analysis.title} · hasil PostGIS</Tooltip></GeoJSON>)}{target&&<CircleMarker center={[target.lat,target.lon]} radius={9} pathOptions={{color:"#0f172a",fillColor:"#ffffff",fillOpacity:1,weight:3}}><Tooltip permanent direction="top" offset={[0,-8]}>{target.label}</Tooltip></CircleMarker>}</MapContainer>
      {showNorthArrow&&<div className={styles.northArrow} aria-label="Arah utara"><b>N</b><span aria-hidden="true">↑</span></div>}
      {(showLayerControl||showLegend)&&<aside className="runtime-layer-list" aria-label={showLayerControl?"Kontrol layer peta":"Legenda peta"}><strong>{showLayerControl?"Layer Peta":"Legenda Peta"}</strong>{payload.layers.map((layer)=>{const presentation=isVectorLayer(layer)?labelPresentations[layer.datasetVersionId]:null;const labelSummary=showLabels&&presentation?.field?` · label ${presentation.field} z≥${presentation.minZoom}${presentation.mode==="auto"?" auto":""}`:"";const kindSummary=layer.dataKind==="RASTER"?`RASTER · ${rasterSummary(layer)}`:`${layer.role}${labelSummary}`;return showLayerControl?<label key={layer.datasetVersionId}><input type="checkbox" checked={visibility[layer.datasetVersionId]??layer.visible} onChange={(event)=>setVisibility((current)=>({...current,[layer.datasetVersionId]:event.target.checked}))}/><i className={"runtime-layer-dot "+layer.role.toLowerCase()}/><span>{layer.title}</span><small>{kindSummary}</small></label>:<span key={layer.datasetVersionId}><i className={"runtime-layer-dot "+layer.role.toLowerCase()}/><span>{layer.title}</span><small>{kindSummary}</small></span>;})}{analyses.filter((analysis)=>analysis.geojson).map((analysis)=>showLayerControl?<label key={analysis.toolId}><input type="checkbox" checked={analysisVisibility[analysis.toolId]??true} onChange={(event)=>setAnalysisVisibility((current)=>({...current,[analysis.toolId]:event.target.checked}))}/><i className="runtime-layer-dot" style={{background:analysisColor(analysis.toolId)}}/><span>Hasil {analysis.title}</span><small>POSTGIS</small></label>:<span key={analysis.toolId}><i className="runtime-layer-dot" style={{background:analysisColor(analysis.toolId)}}/><span>Hasil {analysis.title}</span><small>POSTGIS</small></span>)}</aside>}
    </div>
    {showDataPanel&&<section className={styles.dataPanel} aria-live="polite"><div className={styles.dataPanelHead}><div><span>Data Panel</span><strong>{selectedData?.layerTitle??"Pilih feature vector pada peta"}</strong></div>{selectedData&&<small>{selectedData.role}</small>}</div>{selectedData?selectedData.entries.length?<dl>{selectedData.entries.map(([key,value])=><div key={key}><dt>{key}</dt><dd>{value}</dd></div>)}</dl>:<p>Feature terpilih tidak memiliki atribut sederhana yang dapat ditampilkan.</p>:<p>Data Panel membaca atribut feature vector. Raster tetap tampil sebagai layer citra analitis.</p>}</section>}
    {showAttributeTable&&<AssessmentAttributeTable layers={vectorLayers} open={attributeOpen} onOpenChange={setAttributeOpen} activeLayerId={attributeLayerId} onActiveLayerChange={(layerId)=>{setAttributeLayerId(layerId);setSelectedFeature(null);}} selected={selectedFeature} onSelect={(value)=>{setSelectedFeature(value);setVisibility((current)=>({...current,[value.layerId]:true}));}}/>}
    <p className={styles.note}>{legacyMode?"Soal ini dibuat sebelum konfigurasi adaptive tersedia, sehingga GeoLearn mempertahankan kontrol WebGIS lama untuk kompatibilitas.":"Kontrol peta mengikuti QuestionVersion. Raster analitis ditampilkan sebagai layer data dan tetap terpisah dari basemap."}</p>
  </div>;
}
