import {describe,expect,it} from "vitest";
import {hydrateQuestionBankRow} from "./question-bank-model";

function row(overrides:Record<string,unknown>={}){return {id:"q",title:"Soal",subject:null,topic:null,scope:"PRIVATE",questionStatus:"ACTIVE",ownerTeacherId:"teacher",versionId:"v1",versionNumber:1,spatialMode:"location",difficulty:"Mudah",prompt:"Prompt",versionStatus:"DRAFT",stimulusType:"text",responseType:"multiple-choice",hasPublished:false,groupId:null,groupTitle:null,groupStimulusType:null,basemap:"street",mapExperience:"standard",mapInteractions:[],configuredGisTools:[],requiredGisTools:[],datasetCount:0,vectorCount:0,rasterCount:0,datasets:[],media:null,...overrides} as Parameters<typeof hydrateQuestionBankRow>[0];}

describe("Question Bank preview hydration",()=>{
  it("keeps TEXT metadata media-free",()=>expect(hydrateQuestionBankRow(row()).media).toBeNull());
  it("returns exact IMAGE and VIDEO stimulus delivery metadata",()=>{for(const mediaType of ["IMAGE","VIDEO"] as const){const result=hydrateQuestionBankRow(row({stimulusType:mediaType.toLowerCase(),versionId:`${mediaType}-version`,media:{mediaAssetId:`${mediaType}-asset`,title:`${mediaType} title`,mediaType,storageKey:`https://cdn.test/${mediaType}`,altText:"alt",caption:"caption"}}));expect(result.media).toMatchObject({mediaAssetId:`${mediaType}-asset`,mediaType,deliveryUrl:`https://cdn.test/${mediaType}`});}});
  it("keeps WebGIS counts and config from its selected version",()=>{const result=hydrateQuestionBankRow(row({stimulusType:"webgis",versionId:"published-v1",basemap:"terrain",mapExperience:"analysis",mapInteractions:["legend"],configuredGisTools:["buffer"],requiredGisTools:["buffer"],datasetCount:1,vectorCount:1,datasets:[{datasetVersionId:"dv1",title:"Sekolah",role:"SOURCE",dataKind:"VECTOR",bbox:null}]}));expect(result).toMatchObject({versionId:"published-v1",basemap:"terrain",datasetCount:1,media:null});});
  it("does not mix draft media with published WebGIS metadata",()=>{const published=hydrateQuestionBankRow(row({versionId:"v1",versionStatus:"PUBLISHED",stimulusType:"webgis",datasetCount:4,media:null}));const draft=hydrateQuestionBankRow(row({versionId:"v2",versionNumber:2,stimulusType:"image",datasetCount:0,media:{mediaAssetId:"asset-v2",title:"V2",mediaType:"IMAGE",storageKey:"/legacy/v2.png",altText:null,caption:null}}));expect(published.media).toBeNull();expect(published.datasetCount).toBe(4);expect(draft.media?.mediaAssetId).toBe("asset-v2");expect(draft.datasetCount).toBe(0);});
  it("gracefully represents missing media and empty WebGIS layers",()=>{expect(hydrateQuestionBankRow(row({stimulusType:"image"})).media).toBeNull();expect(hydrateQuestionBankRow(row({stimulusType:"webgis"})).datasets).toEqual([]);});
});
